"""Commit and push a CI fix to the PR head branch."""

from __future__ import annotations

import re
import subprocess
from collections.abc import Mapping
from dataclasses import dataclass

from integrations.coding_agent import CodingResult
from integrations.git import (
    BRANCH_FAILED,
    GitCommandError,
    assert_not_protected,
    changed_paths,
    checkout_branch,
    commit_paths,
    current_branch,
    ensure_git_repo,
    file_fingerprints,
    push_branch,
)
from integrations.github.client import resolve_github_token
from integrations.github.tools.ci_fix.context import CiFixContext
from integrations.github.tools.ci_fix.errors import (
    ERR_NO_CHANGES,
    GitHubCiFixError,
)

_GIT_TIMEOUT_SEC = 60
_SUBJECT_MAX = 72
_MARKDOWN_HEADING_RE = re.compile(r"^#{1,6}\s*")
_SUBJECT_SKIP_LABELS = frozenset(
    {"summary", "root cause", "change", "changes", "verification", "test plan"}
)


@dataclass(frozen=True)
class PushResult:
    """Outcome of pushing a CI fix to a PR branch."""

    branch_name: str
    changed_files: list[str]


def checkout_pr_branch(workspace: str, ctx: CiFixContext) -> None:
    """Switch the workspace to the same-repository PR head branch."""
    try:
        ensure_git_repo(workspace)
        assert_not_protected(ctx.head_branch, protected_extra=ctx.base_branch)
        if current_branch(workspace) == ctx.head_branch:
            return
        if _local_branch_exists(workspace, ctx.head_branch):
            checkout_branch(workspace, ctx.head_branch)
            return
        _fetch_branch(workspace, ctx.head_branch)
        checkout_branch(workspace, ctx.head_branch)
    except GitCommandError as exc:
        raise GitHubCiFixError(exc.kind, exc.message, branch_name=ctx.head_branch) from exc


def push_ci_fix(
    workspace: str,
    *,
    ctx: CiFixContext,
    result: CodingResult,
    baseline: Mapping[str, str] | None = None,
    github_token: str | None = None,
) -> PushResult:
    """Commit files changed by the fix run and push the PR head branch."""
    token = resolve_github_token(github_token)
    try:
        ensure_git_repo(workspace)
        if current_branch(workspace) != ctx.head_branch:
            checkout_pr_branch(workspace, ctx)
        changed = _changed_since_baseline(workspace, baseline=baseline)
        if not changed:
            raise GitHubCiFixError(
                ERR_NO_CHANGES,
                f"CI fix for {ctx.owner}/{ctx.repo}#{ctx.number} produced no file changes; no push was made.",
                branch_name=ctx.head_branch,
            )
        commit_paths(workspace, changed, _commit_message(ctx, result.summary))
        push_branch(
            workspace,
            ctx.head_branch,
            base_default=ctx.base_branch,
            token=token or None,
        )
    except GitCommandError as exc:
        raise GitHubCiFixError(exc.kind, exc.message, branch_name=ctx.head_branch) from exc
    return PushResult(branch_name=ctx.head_branch, changed_files=changed)


def _changed_since_baseline(workspace: str, *, baseline: Mapping[str, str] | None) -> list[str]:
    pre_existing = dict(baseline or {})
    current = changed_paths(workspace)
    current_fingerprints = file_fingerprints(workspace, current)
    return [
        path
        for path in current
        if path not in pre_existing or current_fingerprints.get(path, "") != pre_existing[path]
    ]


def _commit_message(ctx: CiFixContext, summary: str) -> str:
    subject_tail = _subject_tail(summary, fallback="repair failing CI")
    subject = f"fix: repair CI for PR #{ctx.number} - {subject_tail}"[:_SUBJECT_MAX]
    lines = [subject, ""]
    if summary.strip():
        lines += [summary.strip(), ""]
    lines.append(f"Generated by OpenSRE from {ctx.url}.")
    return "\n".join(lines)


def _subject_tail(summary: str, *, fallback: str) -> str:
    """Pick a commit-subject fragment from an agent summary.

    Coding agents often start with markdown headings (``## Summary``). Using the
    first raw line produced commits like ``fix: … - ## Summary``; skip those.
    """
    for raw in summary.strip().splitlines():
        line = _MARKDOWN_HEADING_RE.sub("", raw).strip().strip("*").strip()
        if not line or line.lower() in _SUBJECT_SKIP_LABELS:
            continue
        return line
    return fallback


def _local_branch_exists(workspace: str, branch: str) -> bool:
    result = subprocess.run(
        ["git", "show-ref", "--verify", "--quiet", f"refs/heads/{branch}"],
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=_GIT_TIMEOUT_SEC,
        check=False,
    )
    return result.returncode == 0


def _fetch_branch(workspace: str, branch: str) -> None:
    result = subprocess.run(
        ["git", "fetch", "origin", f"{branch}:{branch}"],
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=_GIT_TIMEOUT_SEC,
        check=False,
    )
    if result.returncode != 0:
        raise GitCommandError(
            BRANCH_FAILED,
            f"Could not fetch PR branch '{branch}': {result.stderr.strip()}",
        )


__all__ = ["PushResult", "checkout_pr_branch", "push_ci_fix"]
